openapi: 3.0.2
info:
  title: demo user app
  description: "demo user app description"
  termsOfService: https://editor.swagger.io/
  contact:
    email: example@gmail.com
    url: https://swagger.io/specification/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT
externalDocs:
  description: Find out more about swagger
  url: https://swagger.io/specification/
servers:
  - url: http://localhost:8080/api/users
tags:
  - name: user
    description: Operations about user
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
paths:
  /api/user:
    post:
      tags:
        - user
      summary: Create user
      description: Create user functionality
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: User not found
          content:
            application/json: {}

      x-codegen-request-body-name: body
  /api/user/{id}:
    get:
      tags:
        - user
      summary: Get user by id
      operationId: getUserById
      parameters:
        - name: id
          in: path
          description: 'The id that needs to be fetched. Use 123 for example. '
          required: true
          schema:
            type: string
          example: 123
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: User not found
          content:
            application/json: {}
    delete:
      summary: delete user by id
      tags:
        - User
      parameters:
        - name: id
          in: path
          description: 'The id that needs to be delete user. Use 123 for example. '
          required: true
          schema:
            type: string
          example: 123
      responses:
        200:
          description: successful operation
          content:
            application/json: {}
        404:
          description: User not found
          content:
            application/json: {}
  /api/user/:
    get:
      tags:
        - user
      summary: Get user by user name
      operationId: getAll
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: User not found
          content:
            application/json: {}

#    put:
#      tags:
#        - user
#      summary: Updated user
#      description: This can only be done by the logged in user.
#      operationId: updateUser
#      parameters:
#        - name: username
#          in: path
#          description: name that need to be updated
#          required: true
#          schema:
#            type: string
#      requestBody:
#        description: Updated user object
#        content:
#          '*/*':
#            schema:
#              $ref: '#/components/schemas/User'
#        required: true
#      responses:
#        200:
#          description: successful operation
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/User'
#        400:
#          description: Invalid user supplied
#          content: {}
#        404:
#          description: User not found
#          content: {}
#      x-codegen-request-body-name: body
#    delete:
#      tags:
#        - user
#      summary: Delete user
#      description: This can only be done by the logged in user.
#      operationId: deleteUser
#      parameters:
#        - name: username
#          in: path
#          description: The name that needs to be deleted
#          required: true
#          schema:
#            type: string
#      responses:
#        201:
#          description: operation successful
#          content: {}
#        400:
#          description: Invalid username supplied
#          content: {}
#        404:
#          description: User not found
#          content: {}
components:
  schemas:
    User:
      type: object
      required:
        - name
        - surname
      properties:
        id:
          type: integer
          example: 123
        name:
          type: string
          example: Саша
        surname:
          type: string
          example: Иванов


#  securitySchemes:
#    reflectoring_auth:
#      type: oauth2
#      flows:
#        implicit:
#          authorizationUrl: http://reflectoring.swagger.io/oauth/dialog
#          scopes:
#            write:users: modify users
#            read:users: read users
#    api_key:
#      type: apiKey
#      name: api_key
#      in: header

