openapi: 3.0.2
info:
  title: demo user app
  description: "demo user+account app description"
  termsOfService: https://editor.swagger.io/
  contact:
    email: example@gmail.com
    url: https://swagger.io/specification/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT
externalDocs:
  description: Find out more about swagger
  url: https://swagger.io/specification/
servers:
  - url: http://localhost:8080
tags:
  - name: acc
    description: Operations about acc
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
  - name: user
    description: Operations about user
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io

paths:
  /api/users:
    $ref: "./paths/users.yml"
  /api/users/{id}:
    $ref: "./paths/users_id.yml"
  /api/acc:
    $ref: "./paths/acc.yml"
  /api/acc/{id}:
    $ref: "./paths/acc_id.yml"
