openapi: 3.0.2
# for build full openapi file:
# swagger-cli bundle openapi.yml --outfile _build/openapi.yaml --type yaml
components:
  schemas:

    UserRs: { $ref: "./schemas/user/UserRs.yml" }
    UserRsList: { $ref: "./schemas/user/UserRsList.yml" }
    UserRegistrationRq: { $ref: "./schemas/user/UserRegistrationRq.yml" }
    UserRegistrationRs: { $ref: "./schemas/user/UserRegistrationRs.yml" }
    UserUpdateRq: { $ref: "./schemas/user/UserUpdateRq.yml" }
    UserAccountRs: { $ref: "./schemas/user/UserAccountRs.yml" }

    AccountRs: { $ref: "./schemas/account/AccountRs.yml" }
    AccountRsList: { $ref: "./schemas/account/AccountRsList.yml" }
    AccountUpdateRq: { $ref: "./schemas/account/AccountUpdateRq.yml" }
    AccountRegistrationRq: { $ref: "./schemas/account/AccountRegistrationRq.yml" }
    AccountRegistrationRs: { $ref: "./schemas/account/AccountRegistrationRs.yml" }

    TransactionRs: { $ref: "./schemas/transaction/TransactionRs.yml" }
    TransactionRsList: { $ref: "./schemas/transaction/TransactionRsList.yml" }
    TransactionRegistrationRq: { $ref: "./schemas/transaction/CreateTransactionRq.yml" }
    TransactionRegistrationRs: { $ref: "./schemas/transaction/CreateTransactionRs.yml" }
    TransactionUpdateRq: { $ref: "./schemas/transaction/TransactionUpdateRq.yml" }

info:
  title: demo user app
  description: "demo user+account app description"
  termsOfService: https://editor.swagger.io/ or https://editor-next.swagger.io/
  contact:
    email: example@gmail.com
    url: https://swagger.io/specification/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT
externalDocs:
  description: Find out more about swagger
  url: https://swagger.io/specification/
servers:
  - url: http://localhost:8080
tags:
  - name: account
    description: Operations about account
    externalDocs:
      description: Find out more about our store
      url: https://editor-next.swagger.io/
  - name: user
    description: Operations about user
    externalDocs:
      description: Find out more about our store
      url: https://editor-next.swagger.io/
  - name: transaction
    description: Operations about Transaction
    externalDocs:
      description: Find out more about our store
      url: https://editor-next.swagger.io/
paths:
  /api/users:
    $ref: "./paths/users.yml"
  /api/users/{id}:
    $ref: "./paths/users_id.yml"
  /api/users/{id}/accounts:
    $ref: "./paths/users_id_account.yml"
  /api/account:
    $ref: "./paths/account.yml"
  /api/account/{id}:
    $ref: "./paths/account_id.yml"
  /api/transaction:
    $ref: "./paths/transaction.yml"
  /api/transaction/{id}:
    $ref: "./paths/transaction_id.yml"
