openapi: 3.0.2
info:
  title: demo user app
  description: "demo user+account app description"
  termsOfService: https://editor.swagger.io/ or https://editor-next.swagger.io/
  contact:
    email: example@gmail.com
    url: https://swagger.io/specification/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT
externalDocs:
  description: Find out more about swagger
  url: https://swagger.io/specification/
servers:
  - url: http://localhost:8080
tags:
  - name: account
    description: Operations about account
    externalDocs:
      description: Find out more about our store
      url: https://editor-next.swagger.io/
  - name: user
    description: Operations about user
    externalDocs:
      description: Find out more about our store
      url: https://editor-next.swagger.io/
  - name: transaction
    description: Operations about Transaction
    externalDocs:
      description: Find out more about our store
      url: https://editor-next.swagger.io/
paths:
  /api/users:
    $ref: "./paths/users.yml"
  /api/users/{id}:
    $ref: "./paths/users_id.yml"
  /api/account:
    $ref: "./paths/account.yml"
  /api/account/{id}:
    $ref: "./paths/account_id.yml"
  /api/transaction:
    $ref: "./paths/transaction.yml"
  /api/transaction/{id}:
    $ref: "./paths/transaction_id.yml"

