server:
  port: 8080
  shutdown: graceful

spring:
  main:
    banner-mode: off
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://localhost:5433/account
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
